(() => {
  "use strict";
  const MAX_UPLOAD_BYTES = 25 * 1024 * 1024;
  const MAX_RECORDING_SECONDS = 60;
  const ALLOWED_SUFFIXES = new Set([".wav", ".mp3", ".m4a", ".ogg", ".webm", ".flac"]);
  const RECORDING_TYPES = [{ mimeType: "audio/webm;codecs=opus", extension: ".webm" }, { mimeType: "audio/mp4", extension: ".m4a" }, { mimeType: "audio/webm", extension: ".webm" }];
  const ENTITY_LABELS = Object.freeze({ PER: { name: "Shaxs", className: "entity-per" }, LOC: { name: "Joy", className: "entity-loc" }, ORG: { name: "Tashkilot", className: "entity-org" }, DATE: { name: "Sana/vaqt", className: "entity-date" } });
  const TIMING_FIELDS = Object.freeze([["audio_preprocessing_ms", "time-audio"], ["stt_ms", "time-stt"], ["normalization_ms", "time-normalization"], ["ner_ms", "time-ner"], ["total_ms", "time-total"]]);
  const elements = {
    record: document.getElementById("record-button"), stop: document.getElementById("stop-button"), file: document.getElementById("audio-file"), preview: document.getElementById("audio-preview"), sourceName: document.getElementById("source-name"), timer: document.getElementById("recording-timer"), analyze: document.getElementById("analyze-button"), clear: document.getElementById("clear-button"), health: document.getElementById("health-status"), healthRetry: document.getElementById("health-retry"), activity: document.getElementById("activity-status"), error: document.getElementById("error-message"), results: document.getElementById("results"), empty: document.getElementById("results-empty"), content: document.getElementById("results-content"), raw: document.getElementById("raw-transcript"), normalized: document.getElementById("normalized-transcript"), highlighted: document.getElementById("highlighted-transcript")
  };
  const timingElements = Object.fromEntries(TIMING_FIELDS.map(([field, id]) => [field, document.getElementById(id)]));
  // This closure-scoped state machine deliberately owns every mutable UI value.
  const state = { phase: "idle", operationId: 0, healthOperationId: 0, health: "checking", file: null, previewUrl: null, stream: null, recorder: null, timerId: null, autoStopId: null, recordingStartedAt: 0, analysisController: null, result: null, error: "" };
  const nextOperation = () => { state.operationId += 1; return state.operationId; };
  const isCurrent = (operationId) => operationId === state.operationId;
  const isAudioReady = () => state.file instanceof File;
  const canAnalyze = () => isAudioReady() && state.health === "ok" && state.phase !== "analyzing";
  const isObject = (value) => typeof value === "object" && value !== null && !Array.isArray(value);
  const formatSeconds = (seconds) => `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  const formatMilliseconds = (milliseconds) => `${Math.round(milliseconds).toLocaleString("uz-UZ")} ms`;
  function setActivity(message) { elements.activity.textContent = message; }
  function setError(message) { state.error = message; state.phase = "error"; elements.error.textContent = message; elements.error.hidden = false; elements.error.focus(); }
  function clearError() { state.error = ""; elements.error.textContent = ""; elements.error.hidden = true; }
  function resetTimer() { window.clearInterval(state.timerId); window.clearTimeout(state.autoStopId); state.timerId = null; state.autoStopId = null; elements.timer.textContent = "00:00 / 01:00"; }
  function stopTracks() { if (state.stream) { state.stream.getTracks().forEach((track) => track.stop()); state.stream = null; } }
  function revokePreviewUrl() { if (state.previewUrl) { URL.revokeObjectURL(state.previewUrl); state.previewUrl = null; } elements.preview.removeAttribute("src"); elements.preview.load(); elements.preview.hidden = true; }
  function abortAnalysis() { if (state.analysisController) { state.analysisController.abort(); state.analysisController = null; } }
  function resetResults() { state.result = null; elements.raw.textContent = ""; elements.normalized.textContent = ""; elements.highlighted.replaceChildren(); TIMING_FIELDS.forEach(([field]) => { timingElements[field].textContent = "—"; }); elements.content.hidden = true; elements.empty.hidden = false; }
  function render() { document.body.dataset.phase = state.phase; elements.record.disabled = state.phase === "analyzing" || state.phase === "recording" || state.phase === "requesting-mic"; elements.stop.disabled = state.phase !== "recording"; elements.file.disabled = state.phase === "analyzing"; elements.analyze.disabled = !canAnalyze(); elements.clear.disabled = state.phase === "idle" && !isAudioReady() && !state.result; elements.results.setAttribute("aria-busy", String(state.phase === "analyzing")); elements.health.dataset.health = state.health; }
  function setPreview(file, source) { revokePreviewUrl(); state.file = file; state.previewUrl = URL.createObjectURL(file); elements.preview.src = state.previewUrl; elements.preview.hidden = false; elements.sourceName.textContent = source === "recording" ? `Yozib olindi: ${file.name}` : `Tanlangan fayl: ${file.name}`; }
  function resetAudio() { state.file = null; state.recorder = null; elements.file.value = ""; elements.sourceName.textContent = "Hali audio tanlanmagan."; revokePreviewUrl(); }
  function clearAll() { nextOperation(); abortAnalysis(); resetTimer(); if (state.recorder && state.recorder.state !== "inactive") state.recorder.stop(); stopTracks(); resetAudio(); resetResults(); clearError(); state.phase = "idle"; setActivity("Audio va natijalar tozalandi."); render(); }
  function extensionFor(fileName) { const suffix = fileName.slice(fileName.lastIndexOf(".")).toLowerCase(); return ALLOWED_SUFFIXES.has(suffix) ? suffix : ""; }
  function validateUpload(file) { if (!file || file.size === 0) return "Bo‘sh audio faylni tahlil qilib bo‘lmaydi. Boshqa fayl tanlang."; if (!extensionFor(file.name)) return "Fayl turi qo‘llab-quvvatlanmaydi. WAV, MP3, M4A, OGG, WebM yoki FLAC fayl tanlang."; if (file.size > MAX_UPLOAD_BYTES) return "Fayl 25 MB dan katta. Kichikroq audio fayl tanlang."; return ""; }
  function selectUpload(event) { if (state.phase === "analyzing") return; const file = event.target.files && event.target.files[0]; const message = validateUpload(file); nextOperation(); abortAnalysis(); resetTimer(); stopTracks(); resetResults(); clearError(); if (message) { resetAudio(); setError(message); setActivity("Fayl tanlanmadi."); render(); return; } setPreview(file, "upload"); state.phase = "ready"; setActivity("Audio tayyor. Mahalliy modellarning holati tasdiqlansa tahlilni boshlashingiz mumkin."); render(); }
  function selectRecordingType() { if (!window.MediaRecorder || typeof window.MediaRecorder.isTypeSupported !== "function") return null; return RECORDING_TYPES.find((candidate) => window.MediaRecorder.isTypeSupported(candidate.mimeType)) || null; }
  function recordingExtension(mimeType, fallback) { return mimeType.includes("mp4") || mimeType.includes("m4a") ? ".m4a" : fallback; }
  function updateTimer() { const elapsed = Math.min(MAX_RECORDING_SECONDS, Math.floor((Date.now() - state.recordingStartedAt) / 1000)); elements.timer.textContent = `${formatSeconds(elapsed)} / 01:00`; setActivity(`Yozilmoqda — ${formatSeconds(elapsed)} / 01:00. Yozuv 60 soniyada avtomatik to‘xtaydi.`); }
  function stopRecording() { if (state.phase !== "recording" || !state.recorder) return; resetTimer(); const recorder = state.recorder; state.phase = "requesting-mic"; setActivity("Yozuv yakunlanmoqda…"); render(); if (recorder.state === "inactive") { stopTracks(); setError("Yozuvni yakunlab bo‘lmadi. Qayta urinib ko‘ring yoki audio fayl tanlang."); setActivity("Yozuv yakunlanmadi."); render(); return; } recorder.stop(); }
  async function startRecording() {
    if (state.phase === "analyzing") return;
    const operationId = nextOperation(); abortAnalysis(); resetTimer(); stopTracks(); resetAudio(); resetResults(); clearError();
    if (!window.isSecureContext || !navigator.mediaDevices || typeof navigator.mediaDevices.getUserMedia !== "function") { setError("Mikrofon faqat xavfsiz ulanishda ishlaydi. Faylni tanlab davom etishingiz mumkin."); setActivity("Mikrofon mavjud emas; fayl yuklash ishlashda davom etadi."); render(); return; }
    const type = selectRecordingType();
    if (!type) { setError("Bu brauzer audio yozuv formatini qo‘llab-quvvatlamaydi. Audio faylni tanlab davom eting."); setActivity("Mikrofon yozuvi mavjud emas; fayl yuklash ishlashda davom etadi."); render(); return; }
    state.phase = "requesting-mic"; setActivity("Mikrofon ruxsati so‘ralmoqda…"); render();
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      if (!isCurrent(operationId)) { stream.getTracks().forEach((track) => track.stop()); return; }
      state.stream = stream;
      const chunks = []; const recorder = new MediaRecorder(stream, { mimeType: type.mimeType }); state.recorder = recorder;
      recorder.addEventListener("dataavailable", (event) => { if (event.data.size > 0) chunks.push(event.data); });
      recorder.addEventListener("error", () => { if (isCurrent(operationId)) { nextOperation(); resetTimer(); stopTracks(); resetAudio(); setError("Yozuvni saqlab bo‘lmadi. Audio faylni tanlab davom eting."); setActivity("Yozuvda xatolik yuz berdi."); render(); } });
      recorder.addEventListener("stop", () => { stopTracks(); if (!isCurrent(operationId)) return; if (chunks.length === 0) { setError("Yozuvdan audio olinmadi. Qayta urinib ko‘ring yoki fayl tanlang."); setActivity("Yozuv bo‘sh qoldi."); render(); return; } const mimeType = recorder.mimeType || type.mimeType; const extension = recordingExtension(mimeType, type.extension); const file = new File([new Blob(chunks, { type: mimeType })], `yozuv${extension}`, { type: mimeType }); resetResults(); clearError(); setPreview(file, "recording"); state.phase = "ready"; setActivity("Yozuv tayyor. Tahlil qilish tugmasini bosing."); render(); });
      recorder.start(); state.recordingStartedAt = Date.now(); state.phase = "recording"; updateTimer(); state.timerId = window.setInterval(updateTimer, 1000); state.autoStopId = window.setTimeout(stopRecording, MAX_RECORDING_SECONDS * 1000); render();
    } catch (error) { if (!isCurrent(operationId)) return; const denied = error instanceof DOMException && (error.name === "NotAllowedError" || error.name === "SecurityError"); setError(denied ? "Mikrofonga ruxsat berilmadi. Brauzer sozlamasidan ruxsat bering yoki audio fayl tanlang." : "Mikrofonni ishga tushirib bo‘lmadi. Audio faylni tanlab davom eting."); setActivity("Mikrofon mavjud emas; fayl yuklash ishlashda davom etadi."); stopTracks(); render(); }
  }
  function isValidResult(payload) { return isObject(payload) && typeof payload.raw_transcript === "string" && typeof payload.normalized_transcript === "string" && Array.isArray(payload.entities) && isObject(payload.timing) && TIMING_FIELDS.every(([field]) => typeof payload.timing[field] === "number" && Number.isFinite(payload.timing[field]) && payload.timing[field] >= 0); }
  function safeEntities(entities, transcript) { const ordered = entities.filter(isObject).sort((left, right) => Number(left.start) - Number(right.start) || Number(left.end) - Number(right.end)); const accepted = []; let end = 0; ordered.forEach((entity) => { if (!ENTITY_LABELS[entity.label] || !Number.isInteger(entity.start) || !Number.isInteger(entity.end) || entity.start < end || entity.start < 0 || entity.end > transcript.length || entity.end <= entity.start || typeof entity.text !== "string" || transcript.slice(entity.start, entity.end) !== entity.text) return; accepted.push(entity); end = entity.end; }); return accepted; }
  function renderHighlighted(transcript, entities) { const fragment = document.createDocumentFragment(); let cursor = 0; safeEntities(entities, transcript).forEach((entity) => { fragment.append(document.createTextNode(transcript.slice(cursor, entity.start))); const metadata = ENTITY_LABELS[entity.label]; const mark = document.createElement("mark"); const hasConfidence = typeof entity.score === "number" && Number.isFinite(entity.score); const confidence = hasConfidence ? Math.max(0, Math.min(1, entity.score)) : null; const percentage = confidence === null ? null : Math.round(confidence * 100); const canonical = typeof entity.canonical_text === "string" && entity.canonical_text ? entity.canonical_text : null; const normalized = canonical ? `; normallashgan ism: ${canonical}` : ""; mark.className = metadata.className; mark.dataset.entityLabel = metadata.name; mark.textContent = entity.text; mark.title = (percentage === null ? `${metadata.name}: qoida asosida` : `${metadata.name}: ${percentage}%`) + normalized; mark.setAttribute("aria-label", (percentage === null ? `${metadata.name}: ${entity.text}, qoida asosida topildi` : `${metadata.name}: ${entity.text}, ishonchlilik ${percentage} foiz`) + normalized); fragment.append(mark); cursor = entity.end; }); fragment.append(document.createTextNode(transcript.slice(cursor))); elements.highlighted.replaceChildren(fragment); }
  function renderResult(payload) { elements.raw.textContent = payload.raw_transcript; elements.normalized.textContent = payload.normalized_transcript; renderHighlighted(payload.normalized_transcript, payload.entities); TIMING_FIELDS.forEach(([field]) => { timingElements[field].textContent = formatMilliseconds(payload.timing[field]); }); elements.empty.hidden = true; elements.content.hidden = false; }
  function apiErrorMessage(status, body) { const code = isObject(body) && isObject(body.error) && typeof body.error.code === "string" ? body.error.code : ""; if (status === 503 || code === "model_unavailable") return "Mahalliy modellar hali tayyor emas. Holatni qayta tekshirib, birozdan so‘ng urinib ko‘ring."; if (status === 413 || code === "upload_too_large") return "Audio fayl juda katta. 25 MB dan kichik fayl tanlang."; if (status === 400 || code === "invalid_audio") return "Audio faylni o‘qib bo‘lmadi. Boshqa yoki buzilmagan fayl tanlang."; if (status === 422 || code === "invalid_request") return "Fayl turi yoki yuborilgan ma’lumot mos emas. Qo‘llab-quvvatlanadigan audio fayl tanlang."; return "Tahlil hozir yakunlanmadi. Audio faylni tekshirib, qayta urinib ko‘ring."; }
  async function analyze() {
    if (!canAnalyze() || !state.file) return;
    const operationId = nextOperation(); const controller = new AbortController(); state.analysisController = controller; state.phase = "analyzing"; clearError(); setActivity("Ovoz mahalliy qurilmada matnga o‘girilmoqda va nomlar ajratilmoqda. Bu biroz vaqt olishi mumkin."); render();
    try { const formData = new FormData(); formData.append("file", state.file, state.file.name); const response = await fetch("/api/analyze-audio", { method: "POST", body: formData, signal: controller.signal, headers: { Accept: "application/json" } }); let payload = null; try { payload = await response.json(); } catch (_) { payload = null; } if (!isCurrent(operationId)) return; if (!response.ok) { setError(apiErrorMessage(response.status, payload)); setActivity("Tahlil yakunlanmadi."); render(); return; } if (!isValidResult(payload)) { setError("Natija kutilgan ko‘rinishda kelmadi. Qayta urinib ko‘ring."); setActivity("Natijani xavfsiz ko‘rsatib bo‘lmadi."); render(); return; } state.result = payload; state.phase = "ready"; renderResult(payload); setActivity("Tahlil tayyor. Belgilangan nomlarni normallashtirilgan transkriptda o‘qing."); render(); } catch (error) { if (!isCurrent(operationId) || (error instanceof DOMException && error.name === "AbortError")) return; setError("Mahalliy server bilan bog‘lanib bo‘lmadi. Server ishlayotganini tekshirib, qayta urinib ko‘ring."); setActivity("Tahlil yakunlanmadi."); render(); } finally { if (isCurrent(operationId)) state.analysisController = null; }
  }
  async function checkHealth() { const operationId = ++state.healthOperationId; state.health = "checking"; elements.health.textContent = "Holat tekshirilmoqda…"; render(); try { const response = await fetch("/api/health", { headers: { Accept: "application/json" } }); let payload = null; try { payload = await response.json(); } catch (_) { payload = null; } if (operationId !== state.healthOperationId) return; state.health = response.ok && isObject(payload) && payload.status === "ok" ? "ok" : "unavailable"; elements.health.textContent = state.health === "ok" ? "Mahalliy modellar tayyor" : "Mahalliy modellar mavjud emas"; if (state.health !== "ok") setActivity("Tahlil uchun mahalliy modellar tayyor emas. Qayta tekshirishni sinab ko‘ring."); else if (!state.error && state.phase !== "analyzing" && state.phase !== "recording" && state.phase !== "requesting-mic") { if (state.result) setActivity("Tahlil tayyor. Belgilangan nomlarni normallashtirilgan transkriptda o‘qing."); else if (isAudioReady()) setActivity("Audio tayyor. Tahlil qilish tugmasini bosing."); else setActivity("Avval ovoz manbasini tanlang."); } render(); } catch (_) { if (operationId !== state.healthOperationId) return; state.health = "unavailable"; elements.health.textContent = "Mahalliy serverga ulanib bo‘lmadi"; setActivity("Tahlil uchun mahalliy server mavjud emas. Qayta tekshirishni sinab ko‘ring."); render(); } }
  elements.record.addEventListener("click", startRecording); elements.stop.addEventListener("click", stopRecording); elements.file.addEventListener("change", selectUpload); elements.analyze.addEventListener("click", analyze); elements.clear.addEventListener("click", clearAll); elements.healthRetry.addEventListener("click", checkHealth);
  window.addEventListener("pagehide", () => { nextOperation(); abortAnalysis(); resetTimer(); stopTracks(); revokePreviewUrl(); });
  render(); checkHealth();
})();
